### ISSUE TITLE
got error when `bs init`

### ISSUE THREAD

**Issue by czhiling** [sinedied/backslide#19]
Thanks a lot for backslide. 

I could not get backslide work on my macbook(MacOS 10.13.1 (17B48)). I was following your instruction on  README.md but got following errors:

```
ZMBP:slides czhiling$ bs init
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/backslide/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/usr/local/lib/node_modules/backslide/node_modules/node-sass/lib/extensions.js:128:13)
    at foundBinariesList (/usr/local/lib/node_modules/backslide/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/usr/local/lib/node_modules/backslide/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/usr/local/lib/node_modules/backslide/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/usr/local/lib/node_modules/backslide/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/backslide/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

Any suggestion to solve it?

Zhiling

**Comment by sinedied** [comment]
Seems the `node-sass` package is not installed properly, which version of node/npm are you using?
This kind of error often happens if you change the node version with `n` or `nvm` afterwards.

You can try reinstalling while clearing cache:
```
npm rm -g backslide
npm cache clean
npm i -g backslide
```

**Comment by mdreier** [comment]
What fixed it for me was running:

`npm rebuild node-sass --force`
