### ISSUE TITLE
Not working on Windows 7

### ISSUE THREAD

**Issue by jenokarthic** [sinedied/backslide#7]
I installed Backslide using npm, and when I tried to initialize in a new folder I am getting following error.

```terminal
c:\bs\test>bs init
C:\Program Files\nodejs\node_modules\backslide\backslide.js:374
  _exit(error, code = 1) {
                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\backslide\bin\bs
:2:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

Environment: 
OS: Windows 7 64 Bit
Node: v4.0.0
npm: v3.8.2

**Comment by sinedied** [comment]
> Node: v4.0.0

Node >= 6 is required, as indicated on the main page (and npm should have issued a warning also)

**Comment by jenokarthic** [comment]
After updating to Node v6.0, it is working now.
